# Generated by Django 4.2.1 on 2024-04-02 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='starts_on',
        ),
        migrations.AddField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
