# Generated by Django 4.2.1 on 2024-04-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_remove_event_starts_on_event_starts_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
    ]
