# Generated by Django 4.2.1 on 2024-05-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_event_minimized_note_minimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
    ]
